const data = {
    status:"succes",
    items:[
        {
            id: 1,
            titulo: "Top Victoria blanco y negro",
            precio: 8,
            imagen: require ("../imagenesData/01.jpg"),
            tipo: "tops",
            cantidad: 1
        },
        {
            id: 2,
            titulo:"Top lazo verde",
            precio: 5,
            imagen: require ("../imagenesData/02.jpg"),
            tipo:"tops",
            cantidad: 1,
        },
        {
            id: 3,
            titulo:"Top una manga celeste",
            precio: 5,
            imagen: require ("../imagenesData/03.jpg"),
            tipo:"tops",
            cantidad: 1,
        },
        {
            id: 4,
            titulo: "Top una manga rosa",
            precio: 5,
            imagen: require ("../imagenesData/04.jpg"),
            tipo:"tops",
            cantidad: 1,
        },
        {
            id: 5,
            titulo: "Top lazo rojo",
            precio:5,
            imagen: require ("../imagenesData/05.jpg"),
            tipo: "tops",
            cantidad: 1,
        },
        {
            id: 6,
            titulo: "Top lazo verde",
            precio:5,
            imagen: require ("../imagenesData/06.jpg"),
            tipo: "tops",
            cantidad: 1,
        },
        {
            id: 7,
            titulo: "Top lazo vinotinto",
            precio:5,
            imagen:require ("../imagenesData/07.jpg"),
            tipo: "tops",
            cantidad: 1,
        },
        {
            id: 8,
            titulo: "Top tiritos rosa",
            precio:4,
            imagen: require ("../imagenesData/08.jpg"),
            tipo: "tops",
            cantidad: 1,
        },
        {
            id: 9,
            titulo: "Top tiritos salmon",
            precio:4,
            imagen: require ("../imagenesData/09.jpg"),
            tipo: "tops",
            cantidad: 1,
        },
        {
            id: 10,
            titulo: "Top tiritos ladrillo",
            precio:4,
            imagen: require ("../imagenesData/10.jpg"),
            tipo: "tops",
            cantidad: 1,
        },
        {
            id: 11,
            titulo: "Set franela de rayas y Short de jeans",
            precio: 12,
            imagen: require("../imagenesData/11.jpeg"),
            tipo: "conjuntos",
            cantidad: 1,
        },
        {
            id: 12,
            titulo: "Set Off Sgoulder gris con falda de jeans",
            precio: 14,
            imagen: require("../imagenesData/12.jpeg"),
            tipo: "conjuntos",
            cantidad: 1,
        },
        {
            id: 13,
            titulo:"Set top con mono rosa",
            precio:17,
            imagen: require("../imagenesData/13.jpeg"),
            tipo: "conjuntos",
            cantidad: 1,
        },
        {
            id: 14,
            titulo: "Franela negra manga larga con short negro",
            precio:12,
            imagen: require("../imagenesData/14.jpg"),
            tipo: "conjuntos",
            cantidad: 1,
        },
        {
            id: 15,
            titulo: "Conjunto franela cuello rendondo rosa con short de jeans",
            precio: 13,
            imagen: require("../imagenesData/15.jpeg"),
            tipo: "conjuntos",
            cantidad: 1,
        },
        {
            id: 16,
            titulo: "Set top con mono negro",
            precio: 17,
            imagen: require("../imagenesData/16.jpg"),
            tipo: "conjuntos",
            cantidad: 1,
        },
        {
            id: 17,
            titulo: "Conjunto a raya blanco y negro",
            precio:20,
            imagen: require("../imagenesData/17.jpeg"),
            tipo: "conjuntos",
            cantidad: 1,
        },
        {
            id:18 ,
            titulo: "Franela fucsia con vuelitos" ,
            precio: 8,
            imagen: require("../imagenesData/18.jpg"),
            tipo: "franelas",
            cantidad: 1,
        },
        {
            id: 19,
            titulo: "Franela con vuelitos blanca y celeste",
            precio: 8,
            imagen: require("../imagenesData/19.jpg"),
            tipo: "franelas",
            cantidad: 1,
        },
        {
            id: 20,
            titulo: "Franela basica a rayas naranja y blanco" ,
            precio: 9,
            imagen: require("../imagenesData/20.jpg"),
            tipo: "franelas",
            cantidad: 1,
        },
        {
            id: 21,
            titulo: "franela basica color ladrillo",
            precio:9,
            imagen: require("../imagenesData/21.jpg"),
            tipo: "franelas",
            cantidad: 1,
        },
        {
            id: 22 ,
            titulo: "Franela mmanga larga color Ladrillo",
            precio: 12,
            imagen: require("../imagenesData/22.jpg"),
            tipo: "franelas",
            cantidad: 1,
        },
        {
            id: 23,
            titulo: "franela cuello en V C/B morada",
            precio: 8,
            imagen: require("../imagenesData/23.jpg"),
            tipo: "franelas",
            cantidad: 1,
        },
        {
            id: 24,
            titulo: "franela cuello en V  menta",
            precio: 8,
            imagen: require("../imagenesData/24.jpg"),
            tipo: "franelas",
            cantidad: 1,
        },
        {
            id: 25,
            titulo: "franela estilo parche azul oscuro",
            precio: 10,
            imagen: require("../imagenesData/25.jpg"),
            tipo: "franelas",
            cantidad: 1,
        },
        {
            id: 26,
            titulo: "franela blanca C/B",
            precio: 8,
            imagen: require("../imagenesData/26.jpg"),
            tipo: "franelas",
            cantidad: 1,
        },
        {
            id: 27,
            titulo: "franela manga larga rosa" ,
            precio: 12,
            imagen: require("../imagenesData/27.jpg"),
            tipo: "franelas",
            cantidad: 1,
        },
        {
            id: 28,
            titulo: "franela manga larga cuello arruchado azul",
            precio:13,
            imagen: require("../imagenesData/28.jpg"),
            tipo: "franelas",
            cantidad: 1,
        },
        {
            id: 29,
            titulo: "shorts malva",
            precio: 7,
            imagen: require("../imagenesData/29.jpg"),
            tipo: "shorts",
            cantidad: 1,
        },
        {
            id: 30,
            titulo: "shorts lazo negro C/rayas",
            precio: 8,
            imagen: require("../imagenesData/30.jpg"),
            tipo: "shorts",
            cantidad: 1,
        },
        {
            id: 31,
            titulo: "short cielo",
            precio: 7,
            imagen: require("../imagenesData/31.jpg"),
            tipo: "shorts",
            cantidad: 1,
        },
        {
            id: 32,
            titulo: "vestido militar",
            precio:12,
            imagen: require("../imagenesData/32.jpg"),
            tipo: "vestidos",
            cantidad: 1,
        },
        {
            id: 33,
            titulo: "vestido cereza",
            precio: 12,
            imagen: require("../imagenesData/33.jpg"),
            tipo: "vestidos",
            cantidad: 1,
        },
        {
            id: 34,
            titulo: "short menta",
            precio: 7,
            imagen: require("../imagenesData/34.jpg"),
            tipo: "shorts",
            cantidad: 1,
        },
    ]
}
export default data